import type { ReactNode } from 'react'
import { Page, PageHeader } from '../components/layout/Page'

/**
 * Privacy and Terms.
 *
 * NOTE: this copy is a DRAFT pending sign-off — it was written for review and
 * has not been approved as final. Deliberately plain-language rather than
 * copied legal boilerplate, matching a small independent app shared with
 * friends and family. It is not legal advice and has not been reviewed by a
 * lawyer.
 */

const UPDATED = '24 August 2026'

function Prose({ children }: { children: ReactNode }) {
  return <div className="flex max-w-prose flex-col gap-5 font-ui text-sm leading-relaxed text-muted">{children}</div>
}

function H2({ children }: { children: ReactNode }) {
  return <h2 className="mt-4 font-display text-lg font-semibold text-text">{children}</h2>
}

function Lead({ children }: { children: ReactNode }) {
  return (
    <p className="rounded-lg border border-accent-warm/25 bg-accent-warm/5 px-5 py-4 font-ui text-base leading-relaxed text-text">
      {children}
    </p>
  )
}

function Updated() {
  return <p className="mt-6 border-t border-border pt-5 font-mono text-[11px] text-muted-subtle">Last updated {UPDATED}</p>
}

export function Privacy() {
  return (
    <Page>
      <PageHeader title="Privacy" />
      <Prose>
        <Lead>
          Popcorn is a small personal project. It stores what it needs to run your watchlist and nothing else, and
          it isn't sold or shared with anyone.
        </Lead>

        <H2>What's stored</H2>
        <ul className="flex list-disc flex-col gap-2 pl-5">
          <li>Your email address, used to sign you in.</li>
          <li>Your watchlist, ratings, review notes, and "why" tags.</li>
          <li>
            What you type into the AI features — your mood description in Pick For Me, and your messages to the Movie
            Assistant — along with what came back, so things like the daily usage limit work.
          </li>
          <li>
            If you choose to add your own Anthropic API key, it's stored encrypted. It's never shown back to you or
            sent to your browser after saving — you can replace or delete it, but not read it.
          </li>
        </ul>

        <H2>What it's used for</H2>
        <p>
          Running the app's features. That's it. It isn't sold, rented, or shared with advertisers, and there's no
          tracking or analytics.
        </p>

        <H2>Third parties your data passes through</H2>
        <ul className="flex list-disc flex-col gap-2 pl-5">
          <li>
            <span className="text-text">TMDB</span> — film metadata, posters, and search. Searches you type go to TMDB.
          </li>
          <li>
            <span className="text-text">Anthropic</span> — powers Pick For Me, Cinema Bridge, Taste DNA, and the Movie
            Assistant. What you type into those features is sent to Anthropic to generate a response.
          </li>
          <li>
            <span className="text-text">Supabase</span> — hosts the database and handles sign-in.
          </li>
          <li>
            <span className="text-text">Resend</span> — delivers feedback you submit to the app author by email.
          </li>
        </ul>
        <p>Each has its own privacy policy, and your data is subject to it once it reaches them.</p>

        <H2>Deleting your account</H2>
        <p>
          Ask and it'll be deleted — your watchlist, ratings, AI history, and any saved API key, permanently. Use the
          feedback form or email directly.
        </p>

        <H2>Changes</H2>
        <p>If this changes meaningfully, the date below changes too.</p>

        <Updated />
      </Prose>
    </Page>
  )
}

export function Terms() {
  return (
    <Page>
      <PageHeader title="Terms of Use" />
      <Prose>
        <Lead>
          This is a hobby project shared with friends and family. It's free, it's provided as-is, and it might break.
        </Lead>

        <H2>Using Popcorn</H2>
        <p>
          Keep it lawful and reasonable. Don't try to access other people's data, don't attack the service, and don't
          use the AI features to generate abusive content.
        </p>

        <H2>Your content</H2>
        <p>
          Your watchlist, ratings, and notes are yours. You're responsible for what you type. It's stored only so the
          app can show it back to you.
        </p>

        <H2>AI features</H2>
        <p>
          Recommendations are generated by an AI model and can be wrong — a film may be mischaracterised, or
          occasionally not exist as described. Treat suggestions as suggestions. Cinema Bridge checks every result
          against TMDB before showing it, but no automated check is perfect.
        </p>

        <H2>Your own API key</H2>
        <p>
          If you add a personal Anthropic API key, usage runs on your account and you're responsible for those costs.
          It's stored encrypted and used only to make requests you trigger. Popcorn can't control Anthropic's pricing
          or availability.
        </p>

        <H2>Availability and no warranty</H2>
        <p>
          Provided "as is", with no warranty of any kind. It may be unavailable, lose data, or be discontinued without
          notice. To the fullest extent the law allows, the author isn't liable for damages arising from using it.
          Keep your own copy of anything you'd miss — Settings has a CSV export.
        </p>

        <H2>Not affiliated</H2>
        <p>This product uses the TMDB API but is not endorsed or certified by TMDB.</p>

        <Updated />
      </Prose>
    </Page>
  )
}
